export * from './authorization/authorization';
export * from './registration/registration';
export * from './profile/profile';
export * from './products/products';
export * from './product/product';
export * from './main/main';
export * from './about-us/about-us';
export * from './page-404/page-404';
export * from './basket/basket';
